/**
 * WhatsApp click-to-chat helpers.
 *
 * We avoid a server-side WhatsApp Business API bot (needs Meta approval,
 * paid plan, verified phone number) and instead use the universal
 * `https://wa.me/?text=...` deep link. On desktop it opens WhatsApp Web;
 * on mobile it opens the native app. The user picks the recipient, so
 * this works for both:
 *   - Marketing share  (recipient = anyone the user wants to tell)
 *   - Send summary     (recipient = the client the manager picks)
 *
 * No API keys. No bot server. Instant.
 */

const MAX_URL_SAFE_MESSAGE = 4000;

export function buildWhatsappShareUrl(opts: {
  /** The text the app pre-fills in WhatsApp. */
  message: string;
  /** Optional phone with country code (digits only, no + or spaces). */
  phone?: string;
}): string {
  const phone = (opts.phone || "").replace(/[^\d]/g, "");
  const text = encodeURIComponent(opts.message.slice(0, MAX_URL_SAFE_MESSAGE));
  return phone
    ? `https://wa.me/${phone}?text=${text}`
    : `https://wa.me/?text=${text}`;
}

/** Opens WhatsApp in a new tab. Blocked popups fall back to same-tab navigation. */
export function openWhatsapp(url: string): void {
  const win = window.open(url, "_blank", "noopener,noreferrer");
  if (!win) window.location.assign(url);
}

/* ----------------- Prebuilt message templates ----------------- */

export function shareFlowMindMessage(appUrl: string): string {
  return (
    `👋 Hey! I've been using *FlowMind* to extract software requirements from ` +
    `documents automatically — AI-powered FR/NFR/Business/System classification, ` +
    `client review portal, the works.\n\n` +
    `It rejects non-SRS docs in <200ms, then uses Qwen 2.5-VL to pull ` +
    `requirements from diagrams too. You can review, approve, or request ` +
    `changes — all in the browser.\n\n` +
    `Check it out:\n${appUrl}`
  );
}

export function documentSummaryMessage(opts: {
  filename: string;
  totalRequirements: number;
  functional?: number;
  nonFunctional?: number;
  business?: number;
  system?: number;
  reviewUrl?: string;
  managerName?: string;
}): string {
  const {
    filename,
    totalRequirements,
    functional = 0,
    nonFunctional = 0,
    business = 0,
    system = 0,
    reviewUrl,
    managerName,
  } = opts;
  const parts: string[] = [];
  parts.push(`📄 *FlowMind — Requirement summary*`);
  if (managerName) parts.push(`_from ${managerName}_`);
  parts.push("");
  parts.push(`*Document:* ${filename}`);
  parts.push(`*Total requirements extracted:* ${totalRequirements}`);
  parts.push("");
  parts.push(`• Functional: ${functional}`);
  parts.push(`• Non-functional: ${nonFunctional}`);
  parts.push(`• Business: ${business}`);
  parts.push(`• System: ${system}`);
  if (reviewUrl) {
    parts.push("");
    parts.push(`👉 Open the full review:\n${reviewUrl}`);
  }
  parts.push("");
  parts.push(`_Generated by FlowMind · AI-powered requirements engineering_`);
  return parts.join("\n");
}

/** The manager's-eye summary, used when copying-to-Slack or similar. */
export function inviteShareMessage(opts: {
  clientName: string;
  email: string;
  tempPassword: string;
  inviteLink: string | null;
  filename?: string;
}): string {
  const lines: string[] = [];
  lines.push(`🔐 *FlowMind review invitation*`);
  lines.push("");
  lines.push(`Hi ${opts.clientName}, you've been invited to review requirements`);
  if (opts.filename) lines.push(`from *${opts.filename}*.`);
  lines.push("");
  lines.push(`*Sign-in email:* ${opts.email}`);
  lines.push(`*Temporary password:* \`${opts.tempPassword}\``);
  if (opts.inviteLink) {
    lines.push("");
    lines.push(`*One-click invite link:*\n${opts.inviteLink}`);
  }
  lines.push("");
  lines.push(`_The password is single-use — change it after signing in._`);
  return lines.join("\n");
}
